### ISSUE TITLE
401 Unauthorized Error

### ISSUE THREAD

**Issue by Gusare124** [ram6ert/bjtuhw_mstodo#3]
here's my feedback from terminal

(base) a0000@magelitedeMacBook-Air bjtuhw_mstodo % STUDENT_ID=23281087 python3 ./main.py
Login at https://www.microsoft.com/link with 33ZRHC62.
Traceback (most recent call last):
  File "/Users/a0000/bjtuhw_mstodo/./main.py", line 64, in <module>
    asyncio.run(main())
  File "/Users/a0000/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/a0000/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0000/miniconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/a0000/bjtuhw_mstodo/./main.py", line 45, in main
    await l.add_todos([ms.Todo(title=f'{hw.course_name}: {hw.title}', end_date=hw.end_at, content=hw.content) for hw in hws])
  File "/Users/a0000/bjtuhw_mstodo/ms.py", line 100, in add_todos
    l = await self.create_task_list_if_not_exist()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0000/bjtuhw_mstodo/ms.py", line 92, in create_task_list_if_not_exist
    l = await self.client.me.todo.lists.post(TodoTaskList(display_name="BJTU Homework"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0000/miniconda3/lib/python3.12/site-packages/msgraph/generated/users/item/todo/lists/lists_request_builder.py", line 91, in post
    return await self.request_adapter.send_async(request_info, TodoTaskList, error_mapping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/a0000/miniconda3/lib/python3.12/site-packages/kiota_http/httpx_request_adapter.py", line 189, in send_async
    await self.throw_failed_responses(response, error_map, parent_span, parent_span)
  File "/Users/a0000/miniconda3/lib/python3.12/site-packages/kiota_http/httpx_request_adapter.py", line 512, in throw_failed_responses
    raise exc
msgraph.generated.models.o_data_errors.o_data_error.ODataError: 
        APIError
        Code: 401
        message: None
        error: MainError(additional_data={}, code='UnknownError', details=None, inner_error=InnerError(additional_data={}, client_request_id='b038b77f-7c7b-452b-8c69-b6049af76d8f', date=DateTime(2024, 11, 22, 8, 58, 35, tzinfo=Timezone('UTC')), odata_type=None, request_id='6e4f59b2-6da5-4f6b-b212-6a9d9927347d'), message='', target=None)

I don't know how to fix it even after asking gpt, so I post it in issues :) hope to get some help

**Comment by Gusare124** [comment]
oh I fix it myself, the problem lies in the access of my account.

visit Microsoft Graph Explorer (https://developer.microsoft.com/graph/graph-explorer)：
	1. 使用你登录的 Microsoft 账号登录。
	2. 在请求中尝试 GET https://graph.microsoft.com/v1.0/me/todo/lists。
	3. 如果权限不足，会看到类似的错误提示，可以据此调整应用权限。
<img width="1059" alt="image" src="https://github.com/user-attachments/assets/1612075a-0dd2-4b52-8169-85a3fe62be1d">

set this two status from consent to unconsent, then the problems are solved.
